{{- if .Values.prometheusRules.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "observability.fullname" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    {{- with .Values.prometheusRules.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.prometheusRules.groups }}
  groups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
