{{- if eq .Values.workload.kind "Deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.workload.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.scaling.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicaCount }}
  {{- end }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "chartname.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.workload.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.observability.openTelemetry.instrumentation.enabled }}
      annotations:
        instrumentation.opentelemetry.io/inject-{{ .Values.observability.openTelemetry.instrumentation.language }}: "true"
      {{- end }}
      labels:
        {{- include "chartname.selectorLabels" . | nindent 8 }}
        {{- with .Values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chartname.serviceAccountName" . }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workload.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.workload.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workingDir }}
          workingDir: {{ . | quote }}
          {{- end }}
          {{- with .Values.workload.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.workload.image.repository }}:{{ .Values.workload.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workload.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.networking.service.port }}
              protocol: TCP
          {{- with .Values.workload.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.config.extraEnvFromConfigMap .Values.config.extraEnvFromSecret .Values.config.sealedSecrets.enabled }}
          envFrom:
            {{- range .Values.config.extraEnvFromConfigMap }}
            - configMapRef:
                name: {{ tpl . $ }}
            {{- end }}
            {{- range .Values.config.extraEnvFromSecret }}
            - secretRef:
                name: {{ tpl . $ }}
            {{- end }}
            {{- if .Values.config.sealedSecrets.enabled }}
            - secretRef:
                name: {{ include "chartname.fullname" . }}
            {{- end }}
          {{- end }}
          {{- if and .Values.workload.probes.startup .Values.workload.probes.startup.enabled }}
          startupProbe:
            {{- $probe := omit .Values.workload.probes.startup "enabled" }}
            {{- if or $probe.tcpSocket $probe.exec $probe.grpc }}
            {{- $probe = omit $probe "httpGet" }}
            {{- end }}
            {{- toYaml $probe | nindent 12 }}
          {{- end }}          
          {{- if and .Values.workload.probes.liveness .Values.workload.probes.liveness.enabled }}
          livenessProbe:
            {{- $probe := omit .Values.workload.probes.liveness "enabled" }}
            {{- if or $probe.tcpSocket $probe.exec $probe.grpc }}
            {{- $probe = omit $probe "httpGet" }}
            {{- end }}
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          {{- if and .Values.workload.probes.readiness .Values.workload.probes.readiness.enabled }}
          readinessProbe:
            {{- $probe := omit .Values.workload.probes.readiness "enabled" }}
            {{- if or $probe.tcpSocket $probe.exec $probe.grpc }}
            {{- $probe = omit $probe "httpGet" }}
            {{- end }}
            {{- toYaml $probe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.workload.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.storage.persistence.enabled }}
              {{- if .Values.storage.persistence.claims }}
                {{- range .Values.storage.persistence.claims }}
            - name: {{ .name }}
              mountPath: {{ .mountPath | default (printf "/data/%s" .name) }}
                {{- end }}
              {{- else }}
            - name: {{ .Values.storage.persistence.name | default "storage" }}
              mountPath: {{ .Values.storage.persistence.mountPath | default "/data" }}
              {{- end }}
            {{- end }}
            {{- range .Values.config.extraConfigMaps }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
            {{- range .Values.config.extraSecrets }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
            {{- with .Values.storage.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.storage.extraVolumeMounts }}
            {{- include "chart.render" (dict "value" .Values.storage.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          {{- with .Values.workload.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.extraContainers }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.storage.persistence.enabled }}
          {{- if .Values.storage.persistence.claims }}
            {{- range .Values.storage.persistence.claims }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "chartname.fullname" $ }}-{{ .name }}
            {{- end }}
          {{- else }}
        - name: {{ .Values.storage.persistence.name | default "storage" }}
          persistentVolumeClaim:
            claimName: {{ default (include "chartname.fullname" .) .Values.storage.persistence.existingClaim }}
          {{- end }}
        {{- end }}
        {{- range .Values.config.extraConfigMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .existingName | default .name }}
            defaultMode: {{ .defaultMode | default 420 }}
        {{- end }}
        {{- range .Values.config.extraSecrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .existingName | default .name }}
            defaultMode: {{ .defaultMode | default 420 }}
        {{- end }}
        {{- with .Values.storage.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.storage.extraVolumes }}
        {{- include "chart.render" (dict "value" .Values.storage.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
      {{- with .Values.workload.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- include "chartname.affinity" . | nindent 8 }} 
      {{- with .Values.workload.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
