{{- if .Values.ingressInternal.enabled }}
{{- $fullName := include "chartname.fullname" . }}
{{- $svcPort := .Values.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-internal
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
  {{- with .Values.ingressInternal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingressInternal.className | default "nginx-internal" }}
  {{- if .Values.ingressInternal.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingressInternal.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ default (printf "%s-tls" $fullName) .Values.ingressInternal.tls.secretName }}
    {{- if .Values.ingressInternal.extraTls }}
    {{- include "chart.render" (dict "value" .Values.ingressInternal.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingressInternal.extraHosts }}
    {{- include "chart.render" (dict "value" .Values.ingressInternal.extraHosts "context" $) | nindent 4 }}
    {{- end }}
    {{- range .Values.ingressInternal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.ingressInternal.extraPaths }}
          {{- include "chart.render" (dict "value" $.Values.ingressInternal.extraPaths "context" $) | nindent 10 }}
          {{- end }}
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}