{{- if .Values.networking.ingressInternal.enabled }}

{{- $fullName := include "chartname.fullname" . }}
{{- $svcPort := .Values.networking.service.port }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-internal
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
  {{- with .Values.networking.ingressInternal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.networking.ingressInternal.className | default "nginx-internal" }}

  {{- if .Values.networking.ingressInternal.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.networking.ingressInternal.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ default (printf "%s-tls" $fullName) .Values.networking.ingressInternal.tls.secretName }}
    {{- if .Values.networking.ingressInternal.extraTls }}
    {{- include "chart.render" (dict "value" .Values.networking.ingressInternal.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.networking.ingressInternal.extraHosts }}
    {{- include "chart.render" (dict "value" .Values.networking.ingressInternal.extraHosts "context" $) | nindent 4 }}
    {{- end }}
    {{- range .Values.networking.ingressInternal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.networking.ingressInternal.extraPaths }}
          {{- include "chart.render" (dict "value" $.Values.networking.ingressInternal.extraPaths "context" $) | nindent 10 }}
          {{- end }}

          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}