apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartname.fullname" . }}
  labels:
    {{- include "chartname.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.service.type }}
  ports:
    - port: {{ .Values.networking.service.port }}
      targetPort: {{ .Values.networking.service.targetPort }}
      protocol: {{ .Values.networking.service.protocol }}
      name: {{ .Values.networking.service.name }}
  selector:
    {{- include "chartname.selectorLabels" . | nindent 4 }}
